### ISSUE TITLE
I do not understand how the fixtures work with normal folder structures

### ISSUE THREAD

**Issue by lazarillo** [cloud-custodian/pytest-terraform#37]
We have what I would think is a fairly typical repository structure, with tests in their own folder parallel to where the "source" code is.  Ours is something like this:

```bash
❯ tree          
.
├── README.md
├── VARIABLES.md
├── examples
│   ├── main.tf
│   └── outputs.tf
├── main.tf
├── outputs.tf
├── test
│   ├── fixture
│   │   ├── main.tf
│   │   ├── outputs.tf
│   │   ├── terraform.tfstate.d
│   │   └── variables.tf
│   └── unit
│       └── test_container_registry_properties_unit.py
└── variables.tf
```

In the case described here, I would have to do something like this in the `test_container_registry_properties_unit.py` file:

```python
@tf.terraform("../..")  ## This is the path where my "main.tf" file lives.
def test_check_acr_tags(../..):  # '../..' is obviously not an acceptable variable name.
    <my code>
```

Do you see my problem?  I don't want to put the actual code being used in production *underneath* where the tests reside.  I also don't want to have to copy them, because the only confident way to do that is with a symbolic link, and I do not want to have a symbolic link in a multi-user shared version controlled repository.

How should this be done?

**Comment by marcoceppi** [comment]
You can set the terraform module search directory in the plugin configuration using `--tf-mod-dir` when running pytest or set `tf.LazyModuleDir` in conftest.py.

Do you have an example repository that I could look at? Otherwise I think you should be able to do:

```
pytest --tf-mod-dir ../../
```

Then use 
```python
@tf.terraform(".", name="main")
def test_check_acr_tags(main):
    <my code>
```

You may also be able to get by with the `../../` and skip so long as you pass the name flag. I'll be honest your use case is not one I think we've considered for this project. It's mostly been used to test python applications that require cloud resources, so for the most part terraform modules are not the object under test but rather artifacts needed to test.

That said, I want to make sure your use-case is supported so I will try with a few terraform modules I maintain to see if I can get this pattern to work and report back.

**Comment by lazarillo** [comment]
Thank you very much!  Let me try this out, and I will follow up whether it solved my situation.  It looks like it will.

I would share the repo, but it is a private and very large repo, so I know I am safe not sharing, and I'm not 100% sure I can share.

If I still have problems, I will create a mock up repo that does what I am trying and I will share it.

**Comment by lazarillo** [comment]
Yes, I have gotten it to successfully work.  Thanks for your help & patience!  :)
